/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#565e74',
        'surface-tint': '#006a63',
        'on-background': '#0b1c30',
        'tertiary-fixed-dim': '#b4c5ff',
        'inverse-on-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        'primary-container': '#0f766e',
        'secondary-fixed-dim': '#bec6e0',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#213145',
        'on-secondary-fixed': '#131b2e',
        'surface-container': '#e5eeff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'surface-dim': '#cbdbf5',
        'on-primary-fixed-variant': '#00504a',
        primary: '#005c55',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#3f465c',
        'secondary-fixed': '#dae2fd',
        'on-error-container': '#93000a',
        'on-secondary-container': '#5c647a',
        'inverse-primary': '#80d5cb',
        'surface-container-low': '#eff4ff',
        'surface-container-highest': '#d3e4fe',
        error: '#ba1a1a',
        'surface-bright': '#f8f9ff',
        outline: '#6e7977',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#003ea8',
        'outline-variant': '#bdc9c6',
        'primary-fixed-dim': '#80d5cb',
        'on-surface-variant': '#3e4947',
        'error-container': '#ffdad6',
        surface: '#f8f9ff',
        background: '#f8f9ff',
        'on-tertiary-container': '#e6e9ff',
        'surface-container-high': '#dce9ff',
        'on-primary-fixed': '#00201d',
        'secondary-container': '#dae2fd',
        'on-surface': '#0b1c30',
        'primary-fixed': '#9cf2e8',
        'on-primary-container': '#a3faef',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-container': '#1e5fe7',
        tertiary: '#0047bf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '1rem',
        'max-width': '72rem',
        'space-xl': '2rem',
        'space-4xl': '6rem',
        'space-xs': '0.5rem',
        'space-2xs': '0.25rem',
        'margin-tablet': '2rem',
        'space-2xl': '3rem',
        'gutter-lg': '2rem',
        'gutter-sm': '1rem',
        'margin-desktop': '3rem',
        'space-lg': '1.5rem',
        'gutter-md': '1.5rem',
        'space-sm': '0.75rem',
        'space-3xl': '4.5rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'body-md': ['Geist', 'sans-serif'],
        'title-md': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['0.9375rem', { lineHeight: '1.5rem', letterSpacing: '-0.005em', fontWeight: '400' }],
        'title-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-md': ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg': ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
